In [7]:
import pandas as pd

In [12]:
df_animais = pd.read_json('/home/ulisses/Estudos/Fast Track AI 2026/Checkpoint 01/dataset_monitoramento_fauna.json')

In [13]:
df_animais.head()

,id_registro,id_camera,data_hora_inicio,duracao_segundos,especie,grupo,individuos,temperatura_c,umidade_pct
0,1,CAM01,2026-05-01 00:04:00,25,Ema,Ave,3,19.3 °C,81.5%
1,2,CAM08,2026-05-01 00:18:00,9,Rã-manteiga,Anfíbio,3,16.6 °C,88.8%
2,3,CAM08,2026-05-01 00:32:00,6,Tatu-canastra,Mamífero,1,16.5 °C,96.3%
3,4,CAM12,2026-05-01 00:37:00,13,Rã-manteiga,Anfíbio,2,19.2 °C,92.1%
4,5,CAM03,2026-05-01 00:39:00,25,Tamanduá-bandeira,Mamífero,1,20.5 °C,82.6%

In [15]:
df_capivaras = df_animais[df_animais['especie'] == 'Capivara']

In [16]:
df_capivaras.head()

,id_registro,id_camera,data_hora_inicio,duracao_segundos,especie,grupo,individuos,temperatura_c,umidade_pct
9,10,CAM12,2026-05-01 00:51:00,31,Capivara,Mamífero,6,20.8 °C,97.1%
22,23,CAM12,2026-05-01 03:06:00,37,Capivara,Mamífero,5,15.7 °C,98.6%
37,38,CAM09,2026-05-01 05:11:00,30,Capivara,Mamífero,11,18.3 °C,96.3%
45,46,CAM10,2026-05-01 06:04:00,4,Capivara,Mamífero,7,18.5 °C,88.0%
47,48,CAM12,2026-05-01 06:08:00,24,Capivara,Mamífero,3,17.7 °C,99.0%

In [20]:
df_capivaras.info()

<class 'pandas.core.frame.DataFrame'>
Index: 731 entries, 9 to 4995
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_registro       731 non-null    int64
 1   id_camera         731 non-null    object
 2   data_hora_inicio  731 non-null    object
 3   duracao_segundos  731 non-null    int64
 4   especie           731 non-null    object
 5   grupo             731 non-null    object
 6   individuos        731 non-null    int64
 7   temperatura_c     709 non-null    object
 8   umidade_pct       699 non-null    object
dtypes: int64(3), object(6)
memory usage: 57.1+ KB

In [31]:
individual = df_capivaras[df_capivaras['individuos'] == 1].shape[0]
total = df_capivaras.shape[0]
percentual = (individual/total)*100

In [32]:
print(individual)
print(total)
print(percentual)

6
731
0.8207934336525308

In [36]:
media = df_capivaras['individuos'].mean()

In [37]:
print(media)

5.954856361149111

In [40]:
# Desafio 1
# Aparições de capivaras individuais são menores que 1% dos registros. 
# Demonstrando que elas preferem andar em grupos, sendo a média apresentada de aproximadamente 6 indivíduos.